Adapt to virtual sensor changes in w3c/sensors#475
w3c/accelerometer pull request #74
Opened 2023-11-22 15:57 UTC by rakuco

The PR above removed the "virtual sensor type" item from the "virtual sensor
metadata" struct and turned it into a string that is referenced from the
automation bits as well as (optionally) defined by a sensor type.

Adapt to it here by removing mentions of `[=virtual sensor metadata/virtual
sensor type=]` from the spec and adding virtual sensor types to each sensor
type defined here.

2023-11-27 23:01 UTC, reillyeon requested changes

2023-11-27 23:01 UTC, reillyeon commented on index.bs
>  :: "`gravity`"
Remove this line.

2023-11-28 11:04 UTC, rakuco commented on index.bs
>  :: "`gravity`"
Oops. Done.

2023-11-28 21:05 UTC, reillyeon approved these changes

2023-11-28 21:05 UTC, merged